# Generated by Django 6.1.2 on 2026-10-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('opis_id', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(db_index=True, max_length=128)),
                ('state', models.CharField(db_index=True, max_length=8)),
                ('rack_id', models.CharField(blank=True, max_length=64, null=True)),
                ('retail_price', models.DecimalField(db_index=True, decimal_places=4, max_digits=8)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
                ('geocode_status', models.CharField(choices=[('EXACT', 'Exact Address/Exit Match'), ('APPROXIMATE', 'Approximate City Match'), ('UNRESOLVED', 'Unresolved')], db_index=True, default='APPROXIMATE', max_length=16)),
                ('provenance', models.CharField(default='us_cities_census_enriched', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='fuel_planne_latitud_da9c01_idx'), models.Index(fields=['state', 'retail_price'], name='fuel_planne_state_49eb3d_idx')],
            },
        ),
    ]
