# Generated by Django 6.1.2 on 2026-10-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstation',
            name='geocode_status',
            field=models.CharField(choices=[('EXACT', 'Verified Station Coordinates (Eligible)'), ('APPROXIMATE', 'Approximate City Centroid (Ineligible by default)'), ('UNRESOLVED', 'Unresolved')], db_index=True, default='APPROXIMATE', max_length=16),
        ),
        migrations.AddIndex(
            model_name='fuelstation',
            index=models.Index(fields=['geocode_status', 'is_active'], name='fuel_planne_geocode_a2cd97_idx'),
        ),
    ]
